# Generated by Django 5.2.4 on 2025-08-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
    ]
