# Generated by Django 5.2.4 on 2025-08-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
